### PR TITLE
Add a workflow that fyne developer can call to help with Fyne QA.

### PR DESCRIPTION
**Pull request by Bluebugs**
This is a move of https://github.com/fyne-io/fyne/pull/4547 .

### CODE REVIEW

**Review by andydotxyz — COMMENTED** [review]
Thanks for this.
Just thinking about naming, should "master" be "latest" to match Go expectations?
Also I worry that "v24" might become confusing if for some reason we move from a .9 to a .10, could it have a separator in there to indicate major vs minor?

**Comment by Bluebugs** [comment]
> Thanks for this. Just thinking about naming, should "master" be "latest" to match Go expectations? Also I worry that "v24" might become confusing if for some reason we move from a .9 to a .10, could it have a separator in there to indicate major vs minor?

I can rename master to latest. As for v24, this workflow has to be updated to match what we care about in term of branch to test (So I do expect it to be renamed to v25 or a v25 to be added later on). Maybe a _ will work, but we are limited by the character we can use. Having a v210, doesn't seem confusing to me as the patch version is not part of the branch name. It might become confusing when fyne start releasing v24.0, but I hope we are very far from that day :-)

**Comment by Bluebugs** [comment]
Changed master to latest.

**Comment by andydotxyz** [comment]
> Having a v210, doesn't seem confusing to me as the patch version is not part of the branch name.

True, but we are not starting from a 3 digit with no ambiguity, the current `v24` moving to `v210` is confusing. 
If you have a better idea than the `_` that's cool but that's the best I could come up with.

**Review by andydotxyz — APPROVED** [review]
Thanks for this.

I think that a follow-up PR will be needed to switch from `fyne/cmd/fyne` to `tools/cmd/fyne` for the `develop` branch (and releases from 2.5 onward).

**Comment by Bluebugs** [comment]
Yes, every time a new major release is done, the old major tests pipeline should be removed/updated to target the new major release with proper name and proper build rules.

**Comment by andydotxyz** [comment]
Absolutely. But as there is a pipeline for develop should it not be using the tooling that will go out with 2.5?

**Pull request merged**
